# This is a basic workflow to help you get started with Actions

name: rootfs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "master" ]
  #pull_request:
  #  branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  boot:
    runs-on: ubuntu-latest
    #strategy:
    #        matrix:
    #            partlabel: [linux]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Build boot
        run: sudo cat ./boot-by-partition-build/boot32/img_info && sudo mkdir ./boot-by-partition-build/boot32/ramdisk && sudo chmod +x ./boot-by-partition-build/* && ./boot-by-partition-build/mkboot ./boot-by-partition-build/boot32 ./boot-by-partition-build/boot.img

      - name: Upload deb packages
        uses: actions/upload-artifact@v4.0.0
        with:
          # Artifact name
          name: nabu-boot 
          #_${{ matrix.partlabel }}
          path: ${{ github.workspace }}/boot-by-partition-build/*.img
  checksums:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: boot
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          pattern: nabu-boot*
      - name: Checksums
        run: sudo md5sum /home/runner/work/ubuntu-xiaomi-nabu/ubuntu-xiaomi-nabu/nabu-boot*/*.img | cut -d ' ' -f 1 >> ${{ github.workspace }}/boot-by-partition-build/checksums.txt

      - name: Upload checksums
        uses: actions/upload-artifact@v4.0.0
        with:
          # Artifact name
          name: checksums
          path: ${{ github.workspace }}/boot-by-partition-build/checksums.txt
          compression-level: 0
  # This workflow contains a single job called "build"
  kernel:
    runs-on: ubuntu-latest
    needs: checksums
    strategy:
            matrix:
                version: [6.7, 6.8]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        
      - name: Install Dependencies
        run: sudo apt update && sudo apt install build-essential gcc-aarch64-linux-gnu bc flex bison 7zip kmod bash cpio binutils tar git wget dpkg libssl-dev

      - name: Build kernel
        run: sudo sh nabu-Kernel_build.sh ${{ matrix.version }}

      - name: Upload deb packages
        uses: actions/upload-artifact@v4.0.0
        with:
          # Artifact name
          name: xiaomi-nabu-debs_${{ matrix.version }}
          path: ${{ github.workspace }}/*.deb
          
  rootfs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: kernel
    strategy:
            matrix:
                desktop: [ubuntu-desktop, plasma-desktop]
                kernel: [6.7, 6.8]
                release: ["23.10"]#, "24.04"]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          pattern: xiaomi-nabu-debs*
      - uses: actions/download-artifact@v4
        with:
          pattern: checksum*
      - name: Install Dependencies
        run: sudo apt update && sudo apt install unzip build-essential gcc-aarch64-linux-gnu bc flex bison 7zip kmod bash cpio binutils tar git wget dpkg libssl-dev

      - name: Build rootfs
        run: sudo sh nabu-rootfs_build.sh ${{ matrix.desktop }} ${{ matrix.kernel }} ${{ matrix.release }}

      - name: Upload rootfs.7z
        uses: actions/upload-artifact@v4.0.0
        with:
          # Artifact name
          name: ubuntu_${{ matrix.release }}_${{ matrix.desktop }}_${{ matrix.kernel }}
          path: rootfs.7z
          compression-level: 0
